### PR TITLE
limiting StakingCoinWeights and EpochAmount, disable ratio plan

### PR DESCRIPTION
**Pull request by dongsam**
## Description

closes: #269 

- https://github.com/tendermint/farming/issues/256

## cherry-picked
- https://github.com/tendermint/farming/pull/259
- https://github.com/tendermint/farming/pull/260

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Appropriate labels applied
- [ ] Targeted PR against correct branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://go.dev/blog/godoc).
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Comment by dongsam** [comment]
I just force push with squash last 2 commit to trigger github workflow

**Review by kogisin — CHANGES_REQUESTED** [review]
`TestIntegrationTestSuite/TestGetCmdQueryParams` is failing.

**Comment by dongsam** [comment]
> `TestIntegrationTestSuite/TestGetCmdQueryParams` is failing.

I just re-run the job, and passed

**Comment by kogisin** [comment]
There's a conflict of `statik.go` file. I think it is due to https://github.com/cosmosquad-labs/squad/pull/268. Let me go check.

**Review by kogisin — APPROVED** [review]

**Pull request merged**
