### PR TITLE
feat: add `HistoricalRewards` gRPC query endpoint

### PR DESCRIPTION
**Pull request by hallazzang**
## Description

This PR adds `HistoricalRewards` gRPC query endpoint and fixes some bugs regarding `EnableAdvanceEpoch` and `EnableRatioPlan` flags.

While the module has been upgraded to `v2`, `REPO` variable in `Makefile` hasn't been updated yet so that it wasn't setting `EnableAdvanceEpoch` and `EnableRatioPlan` flags properly.
Also there was another bug that importing `x/liquidity/simulation/operations.go` automatically sets `EnableRatioPlan` to `true` regardless of `enableRatioPlan` build flag.
These bugs will be fixed through this PR.

## Tasks

- [x] Add `QueryHistoricalRewards` endpoint
- [x] Update API/CLI docs
- [x] Fix bugs with `EnableAdvanceEpoch` and `EnableRatioPlan`

### CODE REVIEW

**Review by kogisin — CHANGES_REQUESTED** [review]
Can you fix the url in [config-test.yml](https://github.com/cosmosquad-labs/squad/blob/historical-rewards-query/config-test.yml#L4) file as well?

**Comment by hallazzang** [comment]
> Can you fix the url in [config-test.yml](https://github.com/cosmosquad-labs/squad/blob/historical-rewards-query/config-test.yml#L4) file as well?

Did that, I'm just wondering... should we update package path in `*.proto` files as well? Like in this file(`proto/mint/v1beta1/mint.proto`):
```
option go_package = "github.com/cosmosquad-labs/squad/x/mint/types";
```

**Comment by kogisin** [comment]
I don't think we need to update package path in `*.proto` files. Doesn't it return an error if you change the path?

**Comment by hallazzang** [comment]
> I don't think we need to update package path in `*.proto` files. Doesn't it return an error if you change the path?

Yes, actually it's working without problem right now. Not updating the path in this PR, let's discuss about it later.

**Pull request merged**
